apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderstore-redis
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
# this will share state between apps using this component
  - name: keyPrefix
    value: name